### ISSUE TITLE
Contact request

### ISSUE THREAD

**Issue by tomaszpalasz** [lithiumFlower/doctotext#13]
Hi.

My name is Tomasz Pałasz and i represent Silvercoders, the author of DocToText.

First of all, I would like to thank you for the work you put into developing this solution. Indeed DocToText has not been developed for a while, but we recently returned to this project with new ideas for development. Could we talk to you about it?

My e-mail: tomasz.palasz@silvercoders.com
Please contact me.

Regards,
Tomasz Pałasz

**Comment by lithiumFlower** [comment]
Thank you for reaching out Tomasz, I'll be in touch.
